ALTER TABLE airlines     ADD COLUMN IF NOT EXISTS logo_url   VARCHAR(500);
ALTER TABLE flights      ADD COLUMN IF NOT EXISTS group_name VARCHAR(100);
ALTER TABLE flight_legs  ADD COLUMN IF NOT EXISTS baggage_kg INTEGER;
