ALTER TABLE flights ADD COLUMN IF NOT EXISTS cost_adult  NUMERIC(12,2);
ALTER TABLE flights ADD COLUMN IF NOT EXISTS cost_child  NUMERIC(12,2);
ALTER TABLE flights ADD COLUMN IF NOT EXISTS cost_infant NUMERIC(12,2);
