ALTER TABLE flights ADD COLUMN IF NOT EXISTS group_type        VARCHAR(20) NOT NULL DEFAULT 'ONE_WAY';
ALTER TABLE flights ADD COLUMN IF NOT EXISTS sector_origin      VARCHAR(10);
ALTER TABLE flights ADD COLUMN IF NOT EXISTS sector_destination VARCHAR(10);
